### ISSUE TITLE
Finalize ComponentDemo/Playground 

### ISSUE THREAD

**Issue by mariuswilms** [atelierdisko/dsk#114]
1. The `ComponentDemo` should be renamed `Playground` as that is how we communicate it.
2. The annotations need to be actually loaded from an asset, this is now possible but, we probably need to use the `src` attribute or use `annotations-src` and have the backend look for attributes that have `-src` attribute suffixes.

**Comment by ChristophLabacher** [comment]
As discussed I implemented 2. by using just the `src` attribute – using `annotations-src` might be an interesting enhancement in the future.
