### ISSUE TITLE
Refinement of built-in Frontend

### ISSUE THREAD

**Issue by ChristophLabacher** [atelierdisko/dsk#50]
## Visual Properties
The base-unit is 8px.

<img width="656" alt="bildschirmfoto 2018-08-03 um 14 24 16" src="https://user-images.githubusercontent.com/7572627/43642707-f300657a-9728-11e8-8590-d15227f5fa87.png">

Color that I forgot: Toothpaste-Green `#52D0AF`. Correction: Gray-800 is `#D9D9D9`
 
## Structure and Grid
<img width="1545" alt="bildschirmfoto 2018-08-03 um 14 23 48" src="https://user-images.githubusercontent.com/7572627/43642722-03bda67a-9729-11e8-866c-eef50ebeddc9.png">

Vertically the grid should be separated into these units:

<img width="1030" alt="bildschirmfoto 2018-08-03 um 14 39 18" src="https://user-images.githubusercontent.com/7572627/43643271-0dda0bb0-972b-11e8-817c-abc7aa563ba2.png">

This means that if, for example, the title is two lines long, the authors section should still be aligned with the description, even though it is in the Side Column.

<img width="1174" alt="bildschirmfoto 2018-08-03 um 14 42 35" src="https://user-images.githubusercontent.com/7572627/43643405-7af153a2-972b-11e8-9f1f-729d144f9dd7.png">

On large screens the Main and Center Columns should be centered, after they have reached their max-width (640px and 240px respectively).

## Overview Page:
When a node has no docs it should show an overview over it’s child nodes:

![desktop hd copy](https://user-images.githubusercontent.com/7572627/44152365-a42ee53a-a0a5-11e8-8ef4-4df3882a1b6d.png)

(Table border is Gray.800)

### Breadcrumbs

<img width="422" alt="bildschirmfoto 2018-08-03 um 14 50 06" src="https://user-images.githubusercontent.com/7572627/43643818-c88cd978-972c-11e8-9fc1-2da56ae8fc90.png">

Sans, Book, Gamma, Gray-600
Margin-bottom: 16px

Hover: Electric-Blue

### Title

<img width="655" alt="bildschirmfoto 2018-08-03 um 14 50 08" src="https://user-images.githubusercontent.com/7572627/43643810-c495eb84-972c-11e8-83da-c7fd1718c446.png">

Sans, Bold, Alpha, Gray-200

### Description

<img width="683" alt="bildschirmfoto 2018-08-03 um 14 50 10" src="https://user-images.githubusercontent.com/7572627/43643805-c11c77de-972c-11e8-91c3-5c91c108855a.png">

Sans, Book, Beta, Gray-200
Margin-bottom: 16px

### Tags

<img width="298" alt="bildschirmfoto 2018-08-15 um 16 11 27" src="https://user-images.githubusercontent.com/7572627/44152457-e1f09ed6-a0a5-11e8-95a9-291651ae6f14.png">

Text: Sans, Bold, Delta, All-Caps, White
Background: Toothpaste-Green
Border Radius: 3px
Spacing Between: 8px

### Meta-Data

<img width="255" alt="bildschirmfoto 2018-08-03 um 14 50 14" src="https://user-images.githubusercontent.com/7572627/43643800-bcfccb36-972c-11e8-9dee-f6c6af225be9.png">

Title: Sans, Bold, Delta, All-Caps, Gray-600
Info: Sans, Book, Gamma, Gray-200
Margin-bottom: 16px

### Assets

<img width="257" alt="bildschirmfoto 2018-08-03 um 14 50 20" src="https://user-images.githubusercontent.com/7572627/43643726-93f814f2-972c-11e8-89c9-dd157fbcd602.png">

Headline: Title: Sans, Bold, Delta, All-Caps, Gray-600
Margin-bottom: 16px

<img width="281" alt="bildschirmfoto 2018-08-03 um 14 50 18" src="https://user-images.githubusercontent.com/7572627/43643740-9a1a467a-972c-11e8-8ffe-7ec337eb97b2.png">

Title: Sans, Bold, Gamma, Gray-200
Arrow: Sans, Bold, Gamma, Gray-800
Info: Sans, Book, Gamma, Gray-600
Margin-bottom: 16px

### Tab Bar

<img width="678" alt="bildschirmfoto 2018-08-03 um 14 57 29" src="https://user-images.githubusercontent.com/7572627/43644048-9efd6630-972d-11e8-988e-4c3c5ba6b90a.png">

Border-bottom: 1px solid Gray-800
Item: Sans, Book, Gamma, Gray-600
Item--isSource: Mono, Book, Gamma, Gray-600
Item--isActive: Gray-200, 2px solid Electric-Blue border on bottom

### P
Sans, Book, Gamma, Gray-200
margin-bottom: 14px

### H1
Sans, Bold, Gamma, Gray-200
Margin-top: 48px
Margin-bottom: 16px

### H2
Sans, Bold, Delta, All-Caps, Gray-600
Margin-top: 32px
Margin-bottom: 4px

### IMG, VIDEO
Width: 100%
Margin-top: 16px
Margin-bottom: 16px

### TABLE, LIST
Same as it currently is

… (WIP)

**Comment by mariuswilms** [comment]
I've implemented modified time (0ad00187ff36ed0a951d752634f40c2932d07614) and file size (15dda294e2163e45665ec519d475366b58a5a360) for node assets as seen in the design. The backend did not yet support them.

**Comment by rodolv1979** [comment]
cool, some sort of telepathy as I was trying to dig into go alone. But it did not work.

**Comment by mariuswilms** [comment]
Merge in dde744bd00036644dccef356675b41d0852809ab
