### ISSUE TITLE
Track which articles/nodes/aspects are used

### ISSUE THREAD

**Issue by wegry** [atelierdisko/dsk#51]
As one of the dsk's customers, alongside it we're currently developing a way to keep track of which articles are used, and how our users get around our design system.

With something like a sqlite DB, recording a triple of the dsk's `(last_visited_node /* nil if the article the initial one from outside the app */, current_node, time)` would allow us to compute things like article view counts. Hopefully, we can also optimize article structure to take common workflows into account.

**Comment by mariuswilms** [comment]
I've found this blog post, might be relevant https://www.pcmaffey.com/roll-your-own-analytics/

**Comment by mariuswilms** [comment]
Thanks for submitting the proposal, unfortuntately the feature is a little bit out of scope. Maybe this can become an external service an be pinged via a small JavaScript snippet, that is included in a custom frontend.
