### ISSUE TITLE
Query/Fragments get lost when linking to other nodes.

### ISSUE THREAD

**Issue by ChristophLabacher** [atelierdisko/dsk#65]
When the `NodeDocTransformer` calls `maybeMakeAbsolute` on a link to a node, the link’s `href` gets replaced with the absolute value of the `data-node` attribute. Unfortunately, fragments and queries that were part of the link’s `href` get lost in the transition.

We need them to be kept in order to be able to link to specific parts of a document.

**Comment by ChristophLabacher** [comment]
This is the critical part of the code: https://github.com/atelierdisko/dsk/blob/search-refinement/node_doc_transformer.go#L260

**Comment by ChristophLabacher** [comment]
Because time was of the essence, I implemented a quick fix on the search-next branch, keeping this issue open so we can create a cleaned up version.

https://github.com/atelierdisko/dsk/commit/8b894afbcfc742b16427a0e37800a513d970a53d

**Comment by mariuswilms** [comment]
Fixed by 89ea8545de997516cdcbc1be3a912dcff4c966d9, will be released with 1.1.1. Thanks for providing the quickfix I was able to built the final patch off.
