### ISSUE TITLE
Clicking "Source" does not work, when there is no .doc-switch

### ISSUE THREAD

**Issue by rockitbaby** [atelierdisko/dsk#66]
Steps to reproduce:

- use example docs
- go to http://127.0.0.1:8080/tree/Content/Glossary
- click 'Source'

In console:
> TypeError: this.main.querySelector(...) is null

caused by page.js line 401 `this.main.querySelector('.doc-switch.active').classList.remove('active');`

**Comment by mariuswilms** [comment]
Fixed by 33769cfef0c29de71c436a0ea120552dfc4e2ffd, as provided through PR #68
