### ISSUE TITLE
Embedded image is distorted

### ISSUE THREAD

**Issue by mariuswilms** [atelierdisko/dsk#79]
The image on i.e. https://rundsk.com/tree/Example-Design-System/Components/Displaying-Content/List doesn't look correct. The styles have a `max-width: 100%` that should be kept, but it is now probably missing `height: auto`, to go over the defined `height` attribute on the element.

![Bildschirmfoto 2019-08-12 um 15 20 56](https://user-images.githubusercontent.com/29702/62868270-88e23600-bd15-11e9-9837-40b089fc1211.png)

As a side-effect this will blow-up the sponsors logos (which are using dimension attributes to size the image). The logos should stay the size they are. We probably need to style them with a selector on the alt attributes? 

![Bildschirmfoto 2019-08-12 um 15 26 38](https://user-images.githubusercontent.com/29702/62868293-98fa1580-bd15-11e9-9aa6-0255eac3a128.png)

We are currently using the Vanilla DSK frontend, which we should keep doing so, as we are testing it at the same time we're using it for the website. Styles specific to the DSK website should optimally not be included in the Vanilla DSK frontend CSS. However if the styling of the sponsors logos is currently the only exception, that's okay for now.

**Comment by ChristophLabacher** [comment]
Maybe the easiest and most appropriate solution would be to add scaled down versions of the sponsors’ logos as assets to the documentation DDT and embed those?

**Comment by mariuswilms** [comment]
I see this distortion has gone away, can you add scaled down versions of the logos, that work both on GitHub and on our website?

**Comment by mariuswilms** [comment]
Thanks to @ricoluetzner the logos now align quite nicely.
