### ISSUE TITLE
Optimize Filtering

### ISSUE THREAD

**Issue by ChristophLabacher** [atelierdisko/dsk#83]
Right now the new frontend for 1.2 uses the API V1 Search endpoint rather than the API V2 Filter endpoint, because we weren’t happy with the quality of the results.

Filter should perform a strict Prefix query on only the title and tags of a node. It is important that searching for multiple tags, separated by spaces is possible.

**Comment by mariuswilms** [comment]
Here we work on support for logical AND https://github.com/atelierdisko/dsk/tree/search-logical-and

**Comment by mariuswilms** [comment]
Implemented in 31ddcc5 and 24ead42, will ship with the next 1.2 release.
