### ISSUE TITLE
Documentation Components: Make paths in src attributes absolute

### ISSUE THREAD

**Issue by ChristophLabacher** [atelierdisko/dsk#84]
In order for documentation component to be able to use assets, we have to make their paths absolute – the same way we already do with the `src` attribute of `img` and `video` elements.

I’d suggest setting the convention that the path in a `src` attribute on any element (custom or not) will be made absolute, if the asset exists in the DDT. This needs to happen in the parsing step in the backend.

**Comment by mariuswilms** [comment]
Example:
```
<ColorSpecimen src="./colors.json" />
```

**Comment by mariuswilms** [comment]
As components are never HTML-parsed in the backend, we need to revert to another method. We should try to reuse (parts of) `maybeMakeAbsolute()` from the `node_doc_transformer.go`

**Comment by mariuswilms** [comment]
Implemented in d8247ba92a1fedd5e03ca3c36f49b8370552a7eb and 2cf1521ccf7910d8969fd69626825d1c298c0940, will ship with next 1.2 release.
