### ISSUE TITLE
CodeBlocks do not render correctly, display `[Object]`

### ISSUE THREAD

**Issue by mariuswilms** [atelierdisko/dsk#87]
CodeBlocks do not render certain content (we are seeing the issue in the official docs)  correctly.

<img width="1207" alt="image" src="https://user-images.githubusercontent.com/29702/63004429-aaa8fd80-be7a-11e9-8bf6-7504207e0f7e.png">

**Comment by ChristophLabacher** [comment]
When using the copy button of CodeBlock, sometimes `<code>[…]</code>` is included in the copied string, even if it is not displayed.

**Comment by mariuswilms** [comment]
Please open a separate issue for that problem, thanks!

**Comment by mariuswilms** [comment]
Fixed in 0ac1c59
