### ISSUE TITLE
Canonical (frontend) configuration

### ISSUE THREAD

**Issue by mariuswilms** [atelierdisko/dsk#94]
The current 1.2 branch frontend can optionally use a `frontendConfig.json` which - currently treated as a node asset - is read in by the frontend. It would be better to find a well known place to put configuration (inside/outside tree?). The configuration can than be queried for via an endpoint `/api/v2/config`. We also need to decide if we spell out config.

https://github.com/atelierdisko/dsk/tree/canonical-frontend-config has some drafts

**Comment by ChristophLabacher** [comment]
I think it is in line with DSK’s philosophy to have the config be placed within the tree.

We might want to name it `dsk.config.json` or something like this, since in the longterm it might also contain configuration for the DSK backend, e.g. with regards to exposing versions via git tags in DSK.

**Comment by mariuswilms** [comment]
Implemented in d4cf519
